version: '3.2'
networks:
  dev:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/16
services:
  webserver:
    build: webserver/
    restart: always
    container_name: backend_webserver
    working_dir: /app
    ports:
      - "8080:80"
    volumes:
      - ./projekt1/:/app:rw,cached
      - ./config/php.ini:/opt/docker/etc/php/php.ini
    networks:
      dev:
        ipv4_address: 10.0.2.1
  mariadb:
    image: mariadb:10.3.27
    container_name: backend_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=strongpassword
    networks:
      dev:
        ipv4_address: 10.0.2.2
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: backend_pma
    depends_on:
      - mariadb
    environment:
      - PMA_HOST=10.0.2.2
    restart: always
    ports: 
      - "8081:80"
    networks:
      dev:
        ipv4_address: 10.0.2.3
    links:
      - mariadb