FROM webdevops/php-apache:7.4-alpine

# WARNING!!!!!
# DONT TRY THIS AT HOME KIDS!!!!!!
USER root
RUN mkdir /var/www/html/upload
RUN chown -R www-data:www-data /var/www/html/upload
RUN chmod -R 777 /var/www/html/upload
# WARNING!!!!!
